/**
 * Neighborhood Helper — data-suburbs.js
 * Twin Cities suburbs: inner (SW Hennepin), northwest (Brooklyn Park/Center/Crystal),
 * west (Plymouth/Wayzata/Minnetonka), and south/Dakota County.
 * Verified May 2026.
 *
 * Statewide/Twin Cities-wide orgs (211, 988, HOME Line, MLA, MACV, MN Warmline,
 * Second Harvest, MN Food HelpLine, AARP Tax, Prepare+Prosper, Emerge MN,
 * MN Recovery, Goodwill Reentry, Amicus) are in data-stpaul.js tagged d:['all']
 * and will surface for all suburb users automatically.
 */

var SUBURB_HOODS = [
  /* Inner SW Suburbs */
  {id:'sub_bloomington', nameKey:'h_sub_bloomington', subKey:'h_sub_bloomington_sub'},
  {id:'sub_richfield',   nameKey:'h_sub_richfield',   subKey:'h_sub_richfield_sub'},
  {id:'sub_edina',       nameKey:'h_sub_edina',       subKey:'h_sub_edina_sub'},
  {id:'sub_slp',         nameKey:'h_sub_slp',         subKey:'h_sub_slp_sub'},
  {id:'sub_hopkins',     nameKey:'h_sub_hopkins',     subKey:'h_sub_hopkins_sub'},
  /* Northwest Suburbs */
  {id:'sub_bpark',       nameKey:'h_sub_bpark',       subKey:'h_sub_bpark_sub'},
  {id:'sub_bcenter',     nameKey:'h_sub_bcenter',     subKey:'h_sub_bcenter_sub'},
  {id:'sub_crystal',     nameKey:'h_sub_crystal',     subKey:'h_sub_crystal_sub'},
  /* West Suburbs */
  {id:'sub_plymouth',    nameKey:'h_sub_plymouth',    subKey:'h_sub_plymouth_sub'},
  {id:'sub_minnetonka',  nameKey:'h_sub_minnetonka',  subKey:'h_sub_minnetonka_sub'},
  /* South / Dakota County */
  {id:'sub_burnsville',  nameKey:'h_sub_burnsville',  subKey:'h_sub_burnsville_sub'},
  {id:'sub_dakota',      nameKey:'h_sub_dakota',      subKey:'h_sub_dakota_sub'}
];

/* Shorthand for all suburb hood IDs */
var _ALL_SUB = [
  'sub_bloomington','sub_richfield','sub_edina','sub_slp','sub_hopkins',
  'sub_bpark','sub_bcenter','sub_crystal',
  'sub_plymouth','sub_minnetonka',
  'sub_burnsville','sub_dakota'
];
var _INNER_SW = ['sub_bloomington','sub_richfield','sub_edina','sub_slp','sub_hopkins'];
var _NW      = ['sub_bpark','sub_bcenter','sub_crystal'];
var _WEST    = ['sub_plymouth','sub_minnetonka'];
var _SOUTH   = ['sub_burnsville','sub_dakota'];

var SUBURB_R = {

  /* ── INNER SW SUBURBS ─────────────────────────────────────────────
     Bloomington · Richfield · Edina · St. Louis Park · Hopkins
     Primary anchors: VEAP and STEP
  ─────────────────────────────────────────────────────────────────── */

  veap:{name:'VEAP - Food, Rent, and Utilities',tagline:'Largest food pantry in Minnesota. Free groceries, rent and utility help for Bloomington, Richfield, Edina, and South Minneapolis (55410/55417/55419). Appointment required. Express walk-in at Door 4. Home delivery for homebound.',tagline_es:'La despensa de alimentos más grande de Minnesota. Comestibles gratuitos, ayuda con renta y servicios públicos para Bloomington, Richfield, Edina y el sur de Minneapolis. Se requiere cita. Entrada directa en Puerta 4. Entrega a domicilio para personas que no pueden salir.',tagline_so:'Raafadda cuntada ee ugu weyn ee Minnesota. Raasinta bilaashka ah, gargaarka kiraadda iyo adeegga oo loogu talagalay Bloomington, Richfield, Edina iyo Koonfurta Minneapolis. Ballan waa loo baahan yahay. Geli toos Albaabka 4.',tagline_hmn:'Chaw muab khoom noj loj tshaj hauv Minnesota. Khoom noj dawb, kev pab xauj tsev thiab nqi hluav taws xob rau Bloomington, Richfield, Edina thiab Qaum Qab Teb Minneapolis. Yuav tsum teem caij. Mus nkag ncaj qha ntawm Rooj Qhib 4.',phone:'952-888-9616',addr:'9600 Aldrich Ave S, Bloomington 55420',hrs:'Mon-Wed & Fri 8am-5pm, Thu 8am-7pm',url:'https://veap.org/',langs:['English','Spanish','Russian'],urg:false,d:_INNER_SW},

  step:{name:'STEP - St. Louis Park Emergency Program',tagline:'Food shelf, rent and utility help, clothing, school supplies, and social services for St. Louis Park residents. Kosher and halal foods available. Emergency walk-in food available.',tagline_es:'Despensa de alimentos, ayuda con renta y servicios públicos, ropa, útiles escolares y servicios sociales para residentes de St. Louis Park. Alimentos kosher y halal disponibles. Comida de emergencia de entrada directa disponible.',tagline_so:'Raafadda cuntada, gargaarka kiraadda iyo adeegga, dhar, saadka dugsiga iyo adeegyada bulshada oo loogu talagalay deganaayaasha St. Louis Park. Cuntada kosher iyo halal ayaa diyaar ah.',tagline_hmn:'Chaw muab khoom noj, kev pab xauj tsev thiab nqi hluav taws xob, ris tsho, cov khoom siv kawm ntawv thiab cov kev pab hauv zej zog rau cov neeg nyob St. Louis Park. Muaj khoom noj kosher thiab halal.',phone:'952-925-4899',addr:'6812 W Lake St, St. Louis Park 55426',hrs:'Mon 8am-4pm, Tue noon-7pm, Wed 8am-4pm, Thu 8am-4pm, Fri 8am-noon',url:'https://www.stepslp.org/',langs:['English'],urg:false,d:['sub_slp']},

  edina_rc:{name:'Edina Resource Center',tagline:'Free connection to community services for Edina residents. Social workers connect you to food, housing, health care, financial help, and more. No appointment needed.',tagline_es:'Conexión gratuita a servicios comunitarios para residentes de Edina. Trabajadores sociales le conectan con alimentos, vivienda, atención médica, ayuda financiera y más. Sin cita previa.',tagline_so:'Xiriirka bilaashka ah oo loo marayo adeegyada bulshada oo loogu talagalay deganaayaasha Edina. Shaqaalaha bulshada waxay kugu xiraan cuntada, guriga, daryeelka caafimaadka, gargaarka maaliyadda iyo wax kale.',tagline_hmn:'Kev txuas dawb rau cov kev pab hauv zej zog rau cov neeg nyob Edina. Cov neeg ua hauj lwm hauv zej zog txuas koj rau zaub mov, tsev nyob, kev kho mob, kev pab nyiaj thiab ntxiv. Tsis tas teem caij.',phone:'952-848-3936',addr:'5701 Normandale Rd, Edina 55424',hrs:'Monday through Friday, business hours',url:'https://edinaresourcecenter.com/',langs:['English'],urg:false,d:['sub_edina']},

  oasis_youth:{name:'Oasis for Youth - South Suburbs',tagline:'Drop-in resource center for youth ages 16-24 in Bloomington, Richfield, and Edina. Case management, housing help, basic needs, and connections to services. No youth in need turned away.',tagline_es:'Centro de recursos de entrada directa para jóvenes de 16 a 24 años en Bloomington, Richfield y Edina. Manejo de casos, ayuda de vivienda y conexiones a servicios. Nadie en necesidad es rechazado.',tagline_so:'Xarunta kheyraadka ee la geli karo si toos ah oo loogu talagalay da-yarta 16-24 jirka ee Bloomington, Richfield iyo Edina. Maamulka kiiska, gargaarka guriga iyo xiriirka adeegyada.',tagline_hmn:'Chaw muab kev pab mus nkag ncaj qha rau cov hluas hnub nyoog 16-24 xyoos hauv Bloomington, Richfield thiab Edina. Kev tswj kho, kev pab tsev nyob thiab kev txuas rau cov kev pab.',phone:'952-512-2061',addr:'2200 W Old Shakopee Rd, Bloomington 55431',hrs:'Mon/Wed/Fri 2-5pm, Tue/Thu noon-5pm',url:'https://www.oasisforyouth.org/',langs:['English'],urg:false,d:_INNER_SW},

  scs_home:{name:'Senior Community Services - Home Maintenance Help',tagline:'Free or low-cost lawn mowing, snow removal, minor repairs, and housekeeping for adults 60+ in Bloomington, Richfield, Edina, Eden Prairie, and St. Louis Park.',tagline_es:'Corte de césped, remoción de nieve, reparaciones menores y limpieza del hogar gratuitas o de bajo costo para adultos de 60 años o más en Bloomington, Richfield, Edina, Eden Prairie y St. Louis Park.',tagline_so:'Jarista cawska bilaashka ah ama qiimaha hoose, masaafada barafka, dayactirka yar iyo nadiifinta guriga oo loogu talagalay dadka 60+ ee Bloomington, Richfield, Edina, Eden Prairie iyo St. Louis Park.',tagline_hmn:'Txiav cỏ dawb lossis nqi qis, tshem daus, kev kho me me thiab kev ntxuav tsev rau cov neeg laus 60+ hauv Bloomington, Richfield, Edina, Eden Prairie thiab St. Louis Park.',phone:'952-746-4046',addr:'Serves SW Hennepin County suburbs - call for service',hrs:'Monday through Friday, business hours',url:'https://seniorcommunity.org/services/home-program/',langs:['English'],urg:false,d:_INNER_SW},

  scs_outreach:{name:'Senior Community Services - Outreach',tagline:'Free in-home counseling and case management for seniors to remain independent in their own homes. Caregiver support groups and consultation. Serves suburban Hennepin County.',tagline_es:'Consejería gratuita en el hogar y manejo de casos para que las personas mayores permanezcan independientes en sus propios hogares. Grupos de apoyo para cuidadores. Sirve a los suburbios del Condado de Hennepin.',tagline_so:'La-tashanaan bilaash ah oo guriga ah iyo maamulka kiiska oo loogu talagalay waayeelka si ay uga sii xornaan doonaan guryahooda. Kooxaha taageerada daryeelayaasha.',tagline_hmn:'Kev tham dawb hauv tsev thiab kev tswj kho rau cov laus kom lawv nyob ywj pheej hauv lawv cov tsev. Cov pawg txhawb rau cov neeg saib xyuas. Ua rau cov zos nyob Hennepin County.',phone:'612-770-7005',addr:'Serves suburban Hennepin County - call for eligibility',hrs:'Monday through Friday, business hours',url:'https://seniorcommunity.org/services/senior-outreach-services/',langs:['English'],urg:false,d:_INNER_SW},

  henn_south_hsc:{name:'Hennepin County South Suburban Service Center',tagline:'Apply for SNAP, cash assistance, health care, emergency assistance, and other county programs. Located at the VEAP campus in Bloomington.',tagline_es:'Solicite SNAP, asistencia en efectivo, atención médica, asistencia de emergencia y otros programas del condado en el Centro de Servicios del Sur del Condado de Hennepin, ubicado en el campus de VEAP en Bloomington.',tagline_so:'Codso SNAP, gargaarka lacagta, daryeelka caafimaadka, gargaarka xaalada degdegga ah iyo barnaamijyada kale ee degmada ee Xarunta Adeegga Koonfurta Degmada Hennepin, oo ku taalla campus-ka VEAP Bloomington.',tagline_hmn:'Thov SNAP, nyiaj pab, kev kho mob, kev pab xwm txheej ceev thiab cov hauj lwm county lwm yam ntawm Hennepin County South Service Center, nyob ntawm VEAP campus hauv Bloomington.',phone:'612-596-1300',addr:'9600 Aldrich Ave S, Bloomington 55420',hrs:'Monday through Friday, 8am-4:30pm',url:'https://www.hennepin.us/en/residents/assistance',langs:['English','Spanish','Somali','Hmong'],urg:false,d:_INNER_SW},

  bloomington_hra:{name:'Bloomington HRA Housing Resources',tagline:'City of Bloomington housing resource hub. Connects residents to rental assistance, VEAP partnership programs, and other housing help. Start here if you live in Bloomington.',tagline_es:'Centro de recursos de vivienda de la Ciudad de Bloomington. Conecta a los residentes con asistencia de alquiler, programas de la asociación VEAP y otras ayudas de vivienda. Comience aquí si vive en Bloomington.',tagline_so:'Xarunta kheyraadka guriga ee Magaalada Bloomington. Kuxirta deganaayaasha gargaarka kiraadda iyo barnaamijyada kaalmada VEAP iyo gargaarka guriga kale. Halkan ka bilow haddaad ku nooshahay Bloomington.',tagline_hmn:'Lub hauv paus chaw pab tsev nyob ntawm Nroog Bloomington. Txuas cov neeg nyob rau kev pab xauj tsev thiab cov hauj lwm tsev nyob. Pib ntawm no yog tias koj nyob hauv Bloomington.',phone:'952-563-8920',addr:'blm.mn/hraresources - or call city hall',hrs:'Monday through Friday, business hours',url:'https://www.bloomingtonmn.gov/hraresources',langs:['English'],urg:false,d:['sub_bloomington']},

  /* ── WEST SUBURBS ──────────────────────────────────────────────────
     Hopkins · Minnetonka · Excelsior · Shorewood · Deephaven
     Primary anchors: ICA Food Shelf and ResourceWest
  ─────────────────────────────────────────────────────────────────── */

  ica_food:{name:'ICA Food Shelf - Hopkins/Minnetonka',tagline:'Choice model food shelf - you shop like a grocery store. Serves Hopkins, Minnetonka, Excelsior, Shorewood, Deephaven, Greenwood, and Woodland. Home delivery available. School-based markets in Hopkins and Minnetonka schools.',tagline_es:'Despensa de alimentos con modelo de elección del cliente: usted hace sus compras como en una tienda. Sirve a Hopkins, Minnetonka, Excelsior, Shorewood, Deephaven, Greenwood y Woodland. Entrega a domicilio disponible.',tagline_so:'Raafadda cuntada ee qaabka doorashada macmiilka: adiga oo xafiisyada badeecadaha u soo iibsanaya. U adeegaya Hopkins, Minnetonka, Excelsior, Shorewood, Deephaven, Greenwood iyo Woodland. Gaadhsiinta guriga ayaa diyaar ah.',tagline_hmn:'Chaw muab khoom noj tus neeg siv xaiv - koj mus yuav khoom zoo li tom khw. Pab Hopkins, Minnetonka, Excelsior, Shorewood, Deephaven, Greenwood thiab Woodland. Muaj kev xa mus tsev.',phone:'952-938-0729',addr:'11588 K-Tel Dr, Minnetonka 55343',hrs:'Mon 10am-6:30pm, Tue 10am-3:30pm, Wed 9am-3:30pm, Thu 10am-3:30pm, 1st & 3rd Sat 10am-noon',url:'https://www.icafoodshelf.org/',langs:['English','Spanish','Somali','Hmong'],urg:false,d:['sub_hopkins','sub_minnetonka']},

  resource_west:{name:'ResourceWest - West Metro Community Services',tagline:'Resource navigation, emergency financial help, employment, and children\'s programs for Hopkins, Minnetonka, Excelsior, Shorewood, Deephaven, Greenwood, and Woodland. Spanish and Somali-speaking staff.',tagline_es:'Orientación de recursos, ayuda financiera de emergencia, empleo y programas para niños para Hopkins, Minnetonka y áreas circundantes. Personal que habla español y somalí disponible.',tagline_so:'Hagaajinta kheyraadka, gargaarka maaliyadda xaalada degdegga ah, shaqo iyo barnaamijyada carruurnimada oo loogu talagalay Hopkins, Minnetonka iyo aagagga deriska ah. Shaqaalaha Isbaanishka iyo Soomaaligu waa joogaan.',tagline_hmn:'Kev coj mus rau cov chaw pab, kev pab nyiaj xwm txheej ceev, hauj lwm thiab cov hauj lwm rau cov menyuam rau Hopkins, Minnetonka thiab cheeb tsam ncig. Muaj neeg hais lus Spanish thiab Somali.',phone:'952-933-3860',addr:'1011 First St S Suite 109, Hopkins 55343',hrs:'Call for appointment hours',url:'https://resourcewest.org/',langs:['English','Spanish','Somali'],urg:false,d:['sub_hopkins','sub_minnetonka']},

  /* ── NORTHWEST SUBURBS ─────────────────────────────────────────────
     Brooklyn Park · Brooklyn Center · Crystal · New Hope · Robbinsdale
     Primary anchors: CEAP, PRISM, NEAR
  ─────────────────────────────────────────────────────────────────── */

  ceap:{name:'CEAP - Food, Seniors, and Family Services',tagline:'Free groceries by curbside appointment (same-day/next-day available). Meals on wheels, senior Silver Selects program (28 frozen meals/month for 60+), thrift store, and baby care packages. Serves Brooklyn Park, Brooklyn Center, and East Champlin.',tagline_es:'Comestibles gratuitos con cita en la acera (disponible el mismo día o al día siguiente). Comidas sobre ruedas, programa Silver Selects para mayores (28 comidas congeladas al mes para personas de 60+), tienda de segunda mano y paquetes para bebés. Sirve a Brooklyn Park, Brooklyn Center y Este de Champlin.',tagline_so:'Raasinta bilaashka ah iyada oo ballan la lahaan karo (isla maalinta ama maalinta xigta). Cuntada gaadhsiinta ah, barnaamijka Silver Selects ee waayeelka (28 cunto barafaysan/bilaha 60+), dukaanka shaybaarka iyo xirmooyinka daryeelka ilmaha.',tagline_hmn:'Khoom noj dawb nrog teem caij ntawm sab nraum rooj (muaj tib hnub lossis hnub tom ntej). Xa zaub mov mus tsev, Silver Selects rau cov laus (28 zaub mov khov/hli rau cov 60+), khw muag khoom qub thiab cov pob rau menyuam yaus.',phone:'763-566-9600',addr:'7051 Brooklyn Blvd, Brooklyn Center 55429',hrs:'Mon-Tue & Thu-Fri 8am-4:30pm, Wed 8am-7pm',url:'https://www.ceap.org/',langs:['English','Spanish'],urg:false,d:_NW},

  near_food:{name:'NEAR Food Shelf - Crystal/New Hope/Robbinsdale',tagline:'Free food shelf serving Crystal, New Hope, and Robbinsdale residents. Monthly visits. School supplies in August for families with current clients. Call to schedule.',tagline_es:'Despensa de alimentos gratuita para residentes de Crystal, New Hope y Robbinsdale. Visitas mensuales. Útiles escolares en agosto para familias con clientes actuales. Llame para hacer una cita.',tagline_so:'Raafadda cuntada bilaashka ah ee u adeegeysa deganaayaasha Crystal, New Hope iyo Robbinsdale. Booqashada bishii. Saadka dugsiga Ogosto. Wac ballanka.',tagline_hmn:'Chaw muab khoom noj dawb ua rau cov neeg nyob Crystal, New Hope thiab Robbinsdale. Mus txhua hli. Cov khoom siv kawm ntawv lub Yim Hli rau cov tsev neeg. Hu rau teem caij.',phone:'763-533-2836',addr:'5209 W Broadway Ave, Crystal 55429',hrs:'Call for current hours',url:'https://www.nearfoodshelf.org/',langs:['English'],urg:false,d:['sub_crystal']},

  prism:{name:'PRISM - Northwest Suburbs Food and Housing',tagline:'Client-choice food shelf and housing assistance (eviction prevention for 250 households/year) in Golden Valley. Serves New Hope, Plymouth, Golden Valley, Crystal, and Robbinsdale. Walk-in welcome.',tagline_es:'Despensa de alimentos con selección del cliente y asistencia de vivienda (prevención de desalojos para 250 hogares al año) en Golden Valley. Sirve a New Hope, Plymouth, Golden Valley, Crystal, Robbinsdale y el Norte de Minneapolis. Entrada directa bienvenida.',tagline_so:'Raafadda cuntada ee doorashada macmiilka iyo gargaarka guriga (ka hortagga masaakinnimada 250 qoys/sannad) ee Golden Valley. U adeegaya New Hope, Plymouth, Golden Valley, Crystal, Robbinsdale iyo Waqooyiga Minneapolis.',tagline_hmn:'Chaw muab khoom noj tus neeg siv xaiv thiab kev pab tsev nyob (tiv thaiv kev ntiab tawm rau 250 lub tsev neeg/xyoos) hauv Golden Valley. Pab New Hope, Plymouth, Golden Valley, Crystal, Robbinsdale thiab Qaum Teb Minneapolis.',phone:'763-529-1350',addr:'1220 Zane Ave N, Golden Valley 55422',hrs:'Mon 11am-7pm, Tue & Wed 9am-4pm, Thu 9am-2pm',url:'https://prismmpls.org/',langs:['English'],urg:false,d:['sub_bpark','sub_bcenter','sub_crystal','mpls_north','mpls_any']},

  hopebridge:{name:'HopeBridge Food Shelf - New Hope/Crystal/Plymouth',tagline:'Appointment-based client-choice food shelf. Primarily serves New Hope, Crystal, and Plymouth but no one is turned away. Limited home delivery 2nd Monday monthly.',tagline_es:'Despensa de alimentos de selección del cliente con cita previa. Sirve principalmente a New Hope, Crystal y Plymouth pero nadie es rechazado. Entrega limitada a domicilio el segundo lunes del mes.',tagline_so:'Raafadda cuntada ee doorashada macmiilka ee ballan ku salaysan. Asalka ahaan u adeegeysa New Hope, Crystal iyo Plymouth laakiin cidna looma diiddo. Gaadhsiinta guriga oo xaddidan Isninkii 2aad bishii.',tagline_hmn:'Chaw muab khoom noj tus neeg siv xaiv nrog teem caij. Feem ntau pab New Hope, Crystal thiab Plymouth tab sis tsis muaj leej twg raug tsis lees txais. Kev xa mus tsev txwv hnub Monday thib 2 ntawm txhua hli.',phone:'763-536-3284',addr:'New Hope Church, New Hope',hrs:'Call for current appointment hours',url:'https://www.hungersolutions.org/resource/hopebridge-food-shelf/',langs:['English'],urg:false,d:_NW},

  capi:{name:'CAPI USA - Immigrant and Refugee Services',tagline:'Connecting immigrants, refugees, and people of color with food, benefits navigation, economic empowerment, and community programs. Brooklyn Center and Brooklyn Park.',tagline_es:'Conecta a inmigrantes, refugiados y personas de color con alimentos, orientación de beneficios, empoderamiento económico y programas comunitarios en Brooklyn Center y Brooklyn Park.',tagline_so:'Ku xira socdaalayaasha, qaxootiga iyo dadka midabka leh cuntada, hagaajinta faa\'iidooyinka, awoodaynta dhaqaale iyo barnaamijyada bulshada ee Brooklyn Center iyo Brooklyn Park.',tagline_hmn:'Txuas cov neeg tsiv teb tsaws chaw, cov neeg tawg rog thiab cov neeg xim ntsej muag nrog zaub mov, kev coj mus rau cov txiaj ntsig, kev txhim kho kev lag luam thiab cov hauj lwm hauv zej zog hauv Brooklyn Center thiab Brooklyn Park.',phone:'763-566-9600',addr:'7051 Brooklyn Blvd, Brooklyn Center 55429',hrs:'Monday through Friday, business hours',url:'https://capiusa.org/',langs:['English','Spanish','Somali','Hmong'],urg:false,d:_NW},

  brooklynk:{name:'BrooklynK - Youth Employment (Brooklyn Park/Center)',tagline:'Connects youth ages 14-21 in Brooklyn Center and Brooklyn Park with jobs, apprenticeships, internships, and mentoring opportunities. Free.',tagline_es:'Conecta a jóvenes de 14 a 21 años en Brooklyn Center y Brooklyn Park con empleos, aprendizajes, pasantías y oportunidades de mentoría. Completamente gratuito.',tagline_so:'Ku xira da-yarta 14-21 jirka ee Brooklyn Center iyo Brooklyn Park shaqooyinka, baranshaha, tareenka iyo fursadaha mentorshipka. Bilaash buuxa.',tagline_hmn:'Txuas cov hluas hnub nyoog 14-21 xyoos hauv Brooklyn Center thiab Brooklyn Park nrog cov hauj lwm, kev kawm ua hauj lwm, kev taug kev kawm thiab cov feem txhawb. Dawb tag nrho.',phone:'763-569-3400',addr:'Brooklyn Center Community Center, 6301 Shingle Creek Pkwy, Brooklyn Center 55430',hrs:'Call for program schedule',url:'https://www.ci.brooklyn-center.mn.us/government/departments/community-development/community-empowerment',langs:['English','Somali'],urg:false,d:_NW},

  henn_nw_hsc:{name:'Hennepin County NW Human Service Center',tagline:'Apply for SNAP, cash assistance, health care, and other county programs. Northwest suburbs location at the CEAP campus in Brooklyn Center.',tagline_es:'Solicite SNAP, asistencia en efectivo, atención médica y otros programas del condado. Ubicación de los suburbios del noroeste en el campus de CEAP en Brooklyn Center.',tagline_so:'Codso SNAP, gargaarka lacagta, daryeelka caafimaadka iyo barnaamijyada kale ee degmada. Goobta suburbiyada waqooyiga galbeed ee campus-ka CEAP ee Brooklyn Center.',tagline_hmn:'Thov SNAP, nyiaj pab, kev kho mob thiab cov hauj lwm county lwm yam. Qhov chaw sab qaum teb hnub poob ntawm CEAP campus hauv Brooklyn Center.',phone:'612-596-1300',addr:'7051 Brooklyn Blvd, Brooklyn Center 55429',hrs:'Monday through Friday, 8am-4:30pm',url:'https://www.hennepin.us/en/residents/assistance',langs:['English','Spanish','Somali','Hmong'],urg:false,d:_NW},

  /* ── WEST METRO OUTER SUBURBS ──────────────────────────────────────
     Plymouth · Wayzata · Orono · Long Lake · Medina
     Primary anchor: IOCP
  ─────────────────────────────────────────────────────────────────── */

  iocp:{name:'IOCP - Interfaith Outreach & Community Partners',tagline:'Food shelf (SuperShelf), thrift store (Resale Select), housing navigation, employment services, and childcare scholarships. Serves Plymouth (west of 494), Hamel, Long Lake, Medina, Minnetonka Beach, Orono, and Wayzata since 1979.',tagline_es:'Despensa de alimentos (SuperShelf), tienda de segunda mano (Resale Select), orientación de vivienda, servicios de empleo y becas de cuidado infantil. Sirve a Plymouth, Hamel, Long Lake, Medina, Minnetonka Beach, Orono y Wayzata desde 1979.',tagline_so:'Raafadda cuntada (SuperShelf), dukaanka shaybaarka (Resale Select), hagaajinta guriga, adeegyada shaqada iyo dalagga daryeelka carruurnimada. U adeegaya Plymouth, Hamel, Long Lake, Medina, Orono iyo Wayzata tan iyo 1979.',tagline_hmn:'Chaw muab khoom noj (SuperShelf), khw muag khoom qub (Resale Select), kev coj mus rau tsev nyob, kev pab hauj lwm thiab cov sib pab rau kev tu menyuam. Pab Plymouth, Hamel, Long Lake, Medina, Orono thiab Wayzata txij xyoo 1979.',phone:'763-489-7500',addr:'1605 County Rd 101 N, Plymouth 55447',hrs:'Call for food shelf appointment hours',url:'https://iocp.org/',langs:['English','Spanish'],urg:false,d:_WEST},

  henn_ridgedale:{name:'Hennepin County Ridgedale Service Center',tagline:'Apply for SNAP, cash assistance, health care, and other county programs. Minnetonka location.',tagline_es:'Solicite SNAP, asistencia en efectivo, atención médica y otros programas del condado en la ubicación de Minnetonka del Centro de Servicios Humanos del Condado de Hennepin.',tagline_so:'Codso SNAP, gargaarka lacagta, daryeelka caafimaadka iyo barnaamijyada kale ee degmada. Goobta Minnetonka ee Xarunta Adeegyada Aadanaha ee Degmada Hennepin.',tagline_hmn:'Thov SNAP, nyiaj pab, kev kho mob thiab cov hauj lwm county lwm yam ntawm qhov chaw Minnetonka ntawm Hennepin County Human Service Center.',phone:'612-596-1300',addr:'12601 Ridgedale Dr, Minnetonka 55305',hrs:'Monday through Thursday, 9am-4:30pm',url:'https://www.hennepin.us/en/residents/assistance',langs:['English','Spanish','Somali','Hmong'],urg:false,d:_WEST},

  /* ── SOUTH SUBURBS / DAKOTA COUNTY ────────────────────────────────
     Burnsville · Apple Valley · Eagan · Lakeville · Farmington · Rosemount
     Primary anchor: 360 Communities
     NOTE: 360 Communities stopped financial assistance Oct 1 2025 (state funding cuts)
  ─────────────────────────────────────────────────────────────────── */

  c360_bville:{name:'360 Communities - Burnsville Food Shelf',tagline:'Free SuperShelf grocery appointments in Burnsville. Housing navigation for tenants in eviction court. Legal kiosks on-site. NOTE: Financial rent/utility assistance ended October 2025 - for emergency cash help call Dakota County at 651-554-5611.',tagline_es:'Citas gratuitas de comestibles SuperShelf en Burnsville. Orientación de vivienda para inquilinos en el tribunal de desalojos. AVISO IMPORTANTE: La asistencia financiera para renta y servicios públicos terminó en octubre de 2025. Para ayuda de emergencia en efectivo llame al Condado de Dakota al 651-554-5611.',tagline_so:'Ballanka bilaashka ah ee raasinta SuperShelf Burnsville. Hagaajinta guriga oo loogu talagalay kiraystayaasha ku jira maxkamadda masaakinnimada. OGOW: Gargaarka maaliyadda ee kiraadda iyo adeegga ayaa dhammaatay Oktoobar 2025. Gargaarka xaaladda degdegga ah ee lacagta wac Degmada Dakota 651-554-5611.',tagline_hmn:'Cov teem caij zaub mov SuperShelf dawb hauv Burnsville. Kev coj mus rau tsev nyob rau cov neeg xauj tsev hauv tsev hais plaub kev ntiab tawm. CEEB TOOM: Kev pab nyiaj xauj tsev thiab nqi hluav taws xob kawg Lub Kaum Hli 2025. Rau kev pab nyiaj xwm txheej ceev hu Dakota County 651-554-5611.',phone:'952-985-5300',addr:'501 E Hwy 13 Suite 112, Burnsville 55337',hrs:'Mon-Thu 9am-4pm, Fri 9am-1pm',url:'https://360communities.org/',langs:['English'],urg:false,d:_SOUTH},

  c360_rosemount:{name:'360 Communities - Rosemount Resource Center',tagline:'Free food shelf and family resource center serving Rosemount and surrounding south Dakota County. Same note: financial assistance ended October 2025. For emergency cash: Dakota County 651-554-5611.',tagline_es:'Despensa de alimentos gratuita y centro de recursos familiares para Rosemount y el sur del Condado de Dakota. AVISO IMPORTANTE: La asistencia financiera terminó en octubre de 2025. Para efectivo de emergencia: Condado de Dakota 651-554-5611.',tagline_so:'Raafadda cuntada bilaashka ah iyo xarunta kheyraadka qoyska ee u adeegeysa Rosemount iyo Koonfurta Degmada Dakota. OGOW: Gargaarka maaliyadda ayaa dhammaatay Oktoobar 2025. Lacagta xaaladda degdegga ah: Degmada Dakota 651-554-5611.',tagline_hmn:'Chaw muab khoom noj dawb thiab chaw pab tsev neeg rau Rosemount thiab qab teb Dakota County. CEEB TOOM: Kev pab nyiaj kawg Lub Kaum Hli 2025. Rau nyiaj xwm txheej ceev: Dakota County 651-554-5611.',phone:'651-322-5113',addr:'14521 Cimarron Ave W, Rosemount 55068',hrs:'Mon-Thu 8am-4pm, Tue evening 5-7pm',url:'https://360communities.org/',langs:['English'],urg:false,d:_SOUTH},

  dakota_hs:{name:'Dakota County Human Services',tagline:'Apply for SNAP, emergency assistance, cash assistance, and healthcare programs. Emergency Assistance available at mnbenefits.mn.gov or by calling. Housing Resource Line: 651-554-5751.',tagline_es:'Solicite SNAP, asistencia de emergencia, asistencia en efectivo y programas de atención médica en el Condado de Dakota. La Asistencia de Emergencia está disponible en mnbenefits.mn.gov o por teléfono.',tagline_so:'Codso SNAP, gargaarka xaalada degdegga ah, gargaarka lacagta iyo barnaamijyada daryeelka caafimaadka ee Degmada Dakota. Gargaarka Xaaladda Degdegga ayaa ku diyaar mnbenefits.mn.gov ama telefoon.',tagline_hmn:'Thov SNAP, kev pab xwm txheej ceev, nyiaj pab thiab cov hauj lwm kev kho mob hauv Dakota County. Kev Pab Xwm Txheej Ceev muaj ntawm mnbenefits.mn.gov lossis hauv xov tooj.',phone:'651-554-5611',addr:'Apply at mnbenefits.mn.gov or call',hrs:'Monday through Friday, 8am-4:30pm',url:'https://www.co.dakota.mn.us/HomeFamily/Assistance/Pages/default.aspx',langs:['English','Spanish','Somali','Hmong'],urg:false,d:_SOUTH},

  mission_outpost:{name:'Mission Outpost - South Dakota County Food Shelf',tagline:'Free food, clothing, linens, and household items by appointment. Serves Burnsville, Apple Valley, Lakeville, Eagan, Savage, Farmington, and Rosemount.',tagline_es:'Alimentos gratuitos, ropa, ropa de cama y artículos para el hogar con cita previa. Sirve a Burnsville, Apple Valley, Lakeville, Eagan, Savage, Farmington y Rosemount.',tagline_so:'Cunto, dhar, googosha sariirta iyo waxyaabaha guriga ee bilaashka ah ballan ku saleysan. U adeegaya Burnsville, Apple Valley, Lakeville, Eagan, Savage, Farmington iyo Rosemount.',tagline_hmn:'Zaub mov dawb, ris tsho, pam pw thiab cov khoom hauv tsev nrog teem caij. Pab Burnsville, Apple Valley, Lakeville, Eagan, Savage, Farmington thiab Rosemount.',phone:'952-898-9311',addr:'13801 Fairview Dr, Burnsville 55337',hrs:'Call for appointment hours',url:'https://popmn.org/mission/mission-outpost',langs:['English'],urg:false,d:_SOUTH},

  isuroon:{name:'Isuroon - Halal Food and East African Services',tagline:'Halal food assistance and culturally specific services for the East African community in Dakota County. Free food, referrals, and community support. Burnsville.',tagline_es:'Asistencia de alimentos halal y servicios culturalmente específicos para la comunidad del África Oriental en el Condado de Dakota. Alimentos gratuitos, referencias y apoyo comunitario en Burnsville.',tagline_so:'Gargaarka cuntada halaal iyo adeegyada gaar ah oo dhaqan ku saleysan oo loogu talagalay bulshada Bariga Afrika ee Degmada Dakota. Cunto bilaash ah, tixraacyada iyo taageero bulshada Burnsville.',tagline_hmn:'Kev pab khoom noj halal thiab cov kev pab tsim nyog rau txoj kab lis kev cai rau zej zog East African hauv Dakota County. Zaub mov dawb, kev xa mus lwm qhov thiab kev txhawb hauv Burnsville.',phone:'952-595-5731',addr:'1103 W Burnsville Pkwy Suite 203, Burnsville 55337',hrs:'Call for current hours',url:'https://isuroon.org/halal-food-assistance',langs:['English','Somali'],urg:false,d:_SOUTH},

  cap_dakota:{name:'CAP - Energy Bill Help (Dakota County)',tagline:'Free help paying heating and energy bills through the LIHEAP program for qualifying households in Scott, Carver, and Dakota counties.',tagline_es:'Ayuda gratuita para pagar facturas de calefacción y energía a través del programa LIHEAP para hogares elegibles en los condados de Scott, Carver y Dakota.',tagline_so:'Gargaar bilaash ah oo loogu talagalay bixinta biilasha kulaylka iyo tamarta adiga oo adeegsanaya barnaamijka LIHEAP ee guryaha xaqiiqda leh ee degmooyinka Scott, Carver iyo Dakota.',tagline_hmn:'Kev pab dawb them cov nqi kub thiab hluav taws xob los ntawm txoj hauj lwm LIHEAP rau cov tsev neeg tsim nyog hauv Scott, Carver thiab Dakota counties.',phone:'952-496-2125',addr:'Serves Scott, Carver, and Dakota counties - apply by phone',hrs:'Monday through Friday, business hours',url:'https://capscottcarver.org/',langs:['English'],urg:false,d:_SOUTH},

  legal_dakota:{name:'Legal Assistance of Dakota County',tagline:'Free legal help for low-income Dakota County residents. Housing, family, and civil cases. Legal kiosks at 360 Communities locations in Burnsville and Rosemount.',tagline_es:'Ayuda legal gratuita para residentes del Condado de Dakota con ingresos bajos. Casos de vivienda, familia y derecho civil. Quioscos legales en las ubicaciones de 360 Communities en Burnsville y Rosemount.',tagline_so:'Gargaar sharci bilaash ah oo loogu talagalay deganaayaasha Degmada Dakota ee dakhliga hoose. Kiisaska guri, qoys iyo madani. Kioskooyinka sharciga ee goobaha 360 Communities Burnsville iyo Rosemount.',tagline_hmn:'Kev pab lij choj dawb rau cov neeg nyob Dakota County muaj nyiaj tau los qis. Cov rooj plaub tsev nyob, tsev neeg thiab cai pej xeem. Cov kiosks lij choj ntawm 360 Communities hauv Burnsville thiab Rosemount.',phone:'952-431-3200',addr:'Kiosks at 360 Communities Burnsville and Rosemount. Call for office appointments.',hrs:'Call for hours. Kiosks available during 360 Communities hours.',url:'https://www.legalaidmn.org/',langs:['English'],urg:false,d:_SOUTH}

};
